"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import { usePathname, useSelectedLayoutSegment } from "next/navigation";
import { Flip, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();

  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <div className="flex flex-col h-[100dvh] w-full">
            {!pathName?.includes("/login") &&
              !pathName?.includes("/signUp") &&
              !pathName?.includes("/error") && <Header toggleSidebar={toggleSidebar}/>}
            <div className="flex h-full w-full">
              {!pathName?.includes("/login") &&
                !pathName?.includes("/signUp") &&
                !pathName?.includes("/error") && <Sidebar isOpen={isSidebarOpen} handleToggleSidebar={toggleSidebar}/>}
              {children}
            </div>
          </div>
          <ToastContainer position="top-right" transition={Flip} />
        </Provider>
      </body>
    </html>
  );
}
